"""rename address

Revision ID: c7dc6d89acaa
Revises: a10f79818b7f
Create Date: 2025-06-16 22:40:46.452180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dc6d89acaa'
down_revision = 'a10f79818b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departmentss', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departmentss', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departmentss', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departmentss', 'location')
    # ### end Alembic commands ###
